### ISSUE TITLE
Over-Overview doc request

### ISSUE THREAD

**Issue by notbenh** [Test-More/Test-Stream#21]
I know that is (in its current state) a proto-release thing but are there plans for the over-overview making its way to a doc somewhere? Currently it seems to be missing just straight up docs. Or did I just sign up to start writing them as I remember them and you correct me when I am wrong because it might be another 13+ days ;)

**Comment by exodist** [comment]
https://metacpan.org/pod/release/EXODIST/Test-Stream-1.302010/lib/Test/Stream/Manual/FromTestBuilder.pod
