### ISSUE TITLE
Improve docs in Test::Stream::Interceptor to elaborate on what is contained in the arrayref.

### ISSUE THREAD

**Issue by notbenh** [Test-More/Test-Stream#23]
I didn't do much more than skim over things but in Test::Stream::Interceptor, there is no mention (that I saw) of the content of the arrayref that is returned from both grab and intercept. In the example where you capture 2 ok asserts, are they both passing? Do non-passing asserts make it in to the array? how do I inspect? would there ever be a need to grab some diag state from a failing captured assert? It looks cool but with out docs I am not sure how I could make it useful.

**Comment by exodist** [comment]
This functionality has been moved to a couple different modules now, but primarily Test::Stream::Plugin::Intercept, and it is much better documented.
