### ISSUE TITLE
is export aliasing backwards? 

### ISSUE THREAD

**Issue by notbenh** [Test-More/Test-Stream#25]
this might just be me, but it seems that the exporter aliasing is backwards? for example from the PODin Test::Stream::Subtest: 

```
   use Test::Stream::Subtest 'subtest_streamed=subtest';
```
Is it odd that you are assigning the $current_name to $name_to_use ? is this a pattern that I have completely missed?

**Comment by exodist** [comment]
I debated this. It might be better to pick an operator other than '=' to use to make it more clear:

```    use Test::Stream::Subtest 'subtest_streamed>>subtest';```

Any other suggestions? I was thinking ```=>``` might also work, but that might be confusing to see inside a ```qw{...}``` or similar.

**Comment by notbenh** [comment]
If it's order dependant then I think that >> implies the correct flow, though if order is not really important then it seems that cribbing the expected flow for assignment as in

```
use Some::Package 'name_I_wil_use_in_this_code=name_used_in_Some::Package'; 
```

...would be just fine.

**Comment by exodist** [comment]
Order is not an issue. We could reverse the args. I would like input from
others to see if there is a general consensus on which order is most
natural.

Could also use the @ operator and call it 'as'  or '@$' could be the
operator, except the '$' would I interpolate...

**Comment by exodist** [comment]
Fixed, adopted the Sub::Exporter syntax foo => { -as => 'xxx' }
