### ISSUE TITLE
Tests fail on < 5.8.9 

### ISSUE THREAD

**Issue by ribasushi** [Test-More/Test-Stream#29]
`threads->error()` did not happen until [threads 1.54 / perl 5.8.9](https://metacpan.org/source/JDHEDDEN/threads-2.02/Changes#L157)

You need to change the logic around https://metacpan.org/source/EXODIST/Test-Stream-1.302007/lib/Test/Stream/Sync.pm#L76, relying on the return value from `join()` alone. Here is an [example dealing with this](https://metacpan.org/source/RURBAN/Devel-PeekPoke-0.04/t/04thread-torture.t#L27-31)

**Comment by exodist** [comment]
thanks

**Comment by exodist** [comment]
Fixed in 43da926bbf5006eaf817a15d589e580af5498074
