### ISSUE TITLE
Ambiguous behaviour of subclassed exporters

### ISSUE THREAD

**Issue by kentfredric** [Test-More/Test-Stream#3]
In the following code, `before_import` is in fact called, indicating that `Bar` is in fact an exporter.

However, it doesn't inherit exports from its parent, despite inheriting the exporter bit, so `test` is not replicated.

Its not clear if this is intentional behaviour or a bug.

```perl
use strict;
use warnings;

BEGIN {

    package Foo;
    use Test::Stream::Exporter;

    default_exports qw/test/;

    sub test {
        print "It worked!\n";
    }
    $INC{'Foo.pm'} = __FILE__;
}

BEGIN {

    package Bar;
    use parent 'Foo';

    sub before_import {
      print "Before import called\n";
    }
    $INC{'Bar.pm'} = __FILE__;
}

BEGIN {

    package Quux;

    use Bar;

    test();
}
```

**Comment by exodist** [comment]
I think that silently inheriting exports would be a surprising behavior. I think that if something subclasses an exporter the 'import' should simply exit immediately unless there is exporter-meta-data already initialized for the class.

**Comment by exodist** [comment]
fixed this in the recent changes
