### ISSUE TITLE
The output of the TAP is not correct when specify the 'NO PLAN' to plan

### ISSUE THREAD

**Issue by magnolia-k** [Test-More/Test-Stream#32]
$ more test.t
    use strict;
    use warnings;

    use Test::Stream -V1;

    plan('NO PLAN');

    ok(1);

    $ perl test.t
    1..NO PLAN
    ok 1
    1..1

'1..NO PLAN' I seem unnecessary.

**Comment by exodist** [comment]
unlike Test::More, Test::Stream plan only takes annu teger. skip_all is a seperate function, and there is no exposed 'no plan' tool because it is discouraged. the underlying system only supports no-plan for legacy use of Test::More.

**Comment by exodist** [comment]
obviously the plan function needs some argument checking :-)

**Comment by magnolia-k** [comment]
Well, I was understanding.

Certainly it is better to add the argument of the check and the appropriate error message.

**Comment by exodist** [comment]
i want this to stay open to remind me to fix the plan() function to do some arg checking.
