### ISSUE TITLE
Equivalent to the 'parent' method of Test::Builder is?

### ISSUE THREAD

**Issue by magnolia-k** [Test-More/Test-Stream#33]
Is there a way judges are whether in the subtest or not?

For example, like the parent method of Test::Builder.

**Comment by exodist** [comment]
Test::Stream::Sync->stack->top will get you the current hub. In q subtest the hub will be a su class of thr nromal hub class with subtest in the package name.

**Comment by exodist** [comment]
sorry, was on my phone there. Test::Stream::Sync->stack->top will get you the current hub to which all events are sent. If you are in a subtest, the hub will be an instance of Test::Stream::Hub::Subtest, which is a subclass of Test::Stream::Hub. To see how many subtests deep you are you can check the 'nested' attribute on the hub, but note that the attribute is only on subtest hubs, not the base class. Also note that there are other subclasses of hub, Subtest is not the only one. Test-Stream itself has 2 subclasses: https://github.com/Test-More/Test-Stream/tree/new_tools/lib/Test/Stream/Hub  depending on what you are doing you may need to be aware of both types.

**Comment by exodist** [comment]
Oh, another note, Test::Stream::Sync is what you would use to get the hub outside of a test context. However If you are in a test function, or need to generate any events then you should actually use this to get the hub:

```
my $ctx = context(); # exported by Test::Stream::Context
my $hub = $ctx->hub;

...

$ctx->release;
return ...;
```

When inside a testing tool you almost certainly want to use the context and whatever hub it tells you to use. The Test::Stream::Sync->stack->top is VERY low-level, and I probably should not have suggested it first.

**Comment by magnolia-k** [comment]
I see.
Thanks!

This issue is just a question, for when considering the future API, to leave?
