### ISSUE TITLE
formatter env var

### ISSUE THREAD

**Issue by exodist** [Test-More/Test-Stream#35]

**Comment by exodist** [comment]
the formatter defaults to TAP. this is correct and helpful. Other formatters qhen needed can be specified, but I suspect it would be helpful to be able to specify the formatter on the command line as opposed to in the module. for example a "pretty" formatter for humans, you want it when you run it yourself, but you want tap when it is run by something else. in this case an env var such as TS_FORMATTER might be handy.

**Comment by magnolia-k** [comment]
+1

**Comment by exodist** [comment]
Fixed in ce62a5ea
