### ISSUE TITLE
It is not described in the document that isnt function and unlike function is gone.

### ISSUE THREAD

**Issue by magnolia-k** [Test-More/Test-Stream#49]
Perhaps it is not so much more is used, I think it is better described in FromTestBuilder.pod.

**Comment by exodist** [comment]
ah yes, I should document them, and explain the alternatives.

**Comment by exodist** [comment]
Actually, I am adding them to the Classic bundle that is being worked on in a branch.

**Comment by magnolia-k** [comment]
:+1:
