### ISSUE TITLE
Mungers facilitate action at a distance

### ISSUE THREAD

**Issue by Leont** [Test-More/Test-Stream#59]
Currently we have munger callbacks that can modify their Event argument. This facilitates action at a distance, and that is Bad™.

Instead, I propose to add filters that may return either the original object, a new one or undef. That way it should be much clearer what's going on.

**Comment by exodist** [comment]
Agreed, largely base don discussion in #perl-qa. I will deprecate mungers with a plan to remove them soon (I don't think anyone uses them yet, but I want to be safe not sorry).

I will add 'filters' where it behaves more in line with your suggestion.

**Comment by exodist** [comment]
https://github.com/Test-More/Test-Stream/pull/62

**Comment by rjbs** [comment]
#62 definitely addresses this problem.  @leont seems pleased, too.  I'm closing this as resolved, after weekly status meeting with @exodist.
