### ISSUE TITLE
Test::Kit broken again :-)

### ISSUE THREAD

**Issue by kaoru** [Test-More/Test-Stream#65]
Hey Chad,

Nice blog post today on blogs.perl.org :-) I see that some recent release of Test::Stream has broken Test::Kit again - time for me to update my nasty uses of your APIs.

The core issues seem to be two:

**1) Test::Stream::Toolset no longer exists**

I was using this for a Test::More-ish import() from Test::Stream::Toolset::before_import()

        if ($Test::Builder::VERSION >= 1.301001) {
            Test::Stream::Exporter->export_to($target);
            Test::Stream::Toolset->export_to($target, qw(is_tester init_tester context before_import));
        }

Does something like that still exist? Where's it moved to?

**2) before_import() is gone**

This is also impacting my strict/warnings hack...

        # special cases for strict and warnings
        #
        # The logic here is copied from Moose which always causes strict and
        # warnings to be enabled when it is used.
        #
        # A comment in Moose::Exporter states:
        #
        # "this works because both pragmas set $^H (see perldoc perlvar) which
        # affects the current compilation - i.e. the file who use'd us - which
        # is why we don't need to do anything special to make it affect that
        # file rather than this one (which is already compiled)"
        #
        # In the Moose code the author simply calls strict->import() in the
        # appropriate import() method and that does the trick. For us working
        # at a bit more of a distance we have to be a bit trickier - adding
        # strict->import() or warnings->import() to the import method on the
        # target class. We do that by wrapping it with Hook::LexWrap::wrap().
        #
        # TODO see if there's a reason for the 1.1 vs 1.3 difference, and find
        # a way to avoid the if statement here.
        #
        # TODO see whether any other pragmata need to be added to the list
        # along with strict and warnings.
        #
        if ($package eq 'strict' || $package eq 'warnings') {
            if ($Test::Builder::VERSION >= 1.301001) {
                wrap "${target}::before_import", post => sub { $package->import(); };
            }
            else {
                wrap "${target}::import", post => sub { $package->import(); };
            }
        }
        else {
            my $fake_package = $class->_create_fake_package($package, $include_hashref->{$package}, $target);
            $fake_package->import::into($target);
        }

Perhaps that hack is no longer necessary and I can use import() in 1.3.x now.

Two problems, but probably one answer as they seem to be related.

------------------

If the Test::Stream modules are still in flux and are likely to change again then feel free to put me in a holding pattern until things settle down a bit.

Thanks man. Keep up the great work :-)

Alex

**Comment by exodist** [comment]
When you last update Test::Kit  we were still in the experimental phase. A little while back we went stable, as such any fixes you make now should not be broken by future releases.

As for your other questions, I do not have time to answer them right now, but I will attempt to come back and answer them.

**Comment by kaoru** [comment]
That's great, thanks for your help.

**Comment by exodist** [comment]
Ok, I looked at Test::Kit. It looks like the code you have to adjust for Test::Stream goes back to a time where Test::More itself was being changed. At one point that plan was scrapped and I decided that making any changes at all to Test::More would be a mistake.

Anyway, the short version is this: You can probably remove all the Test::Stream specific hacks. See if it works doing the same thing for both old and new versions.

**Comment by kaoru** [comment]
Oh... oh wow! That works :-) https://github.com/kaoru/Test-Kit2/commit/759ea5cd025b1e3666bfd62b4abd0a7c29beab6b

Nice work on making backwards compatibility even more straightforward. Thanks for your help.
