### ISSUE TITLE
isa_ok doesn't handle undefined and scalar arguments properly

### ISSUE THREAD

**Issue by mlawren** [Test-More/Test-Stream#69]
Test::Stream appears to generate an internal error when I run the following:

    use strict;
    use warnings;
    use Test::Stream qw/-V1/;
    isa_ok undef, 'Some::Class';

Error:

    Can't call method "isa" on an undefined value at x.t line 5.
    Context was not released! Releasing at destruction.
    Context creation details:
      Package: main
         File: x.t
         Line: 5
         Tool: Test::Stream::Plugin::Core::__ANON__
    
    Trace:  at /home/mark/src/bif/.direnv/perl5/lib/perl5/Test/Stream/Util.pm line 133.
    	eval {...} called at /home/mark/src/bif/.direnv/perl5/lib/perl5/Test/Stream/Util.pm line 133
    	Test::Stream::Plugin::Core::__ANON__() called at x.t line 5
    
    # No tests run!
    # Looks like your test exited with 255 after test #0.

I would expect to see something like "not ok 1 - undef->isa('Some::Class')".

Similarly, if the first argument to isa_ok is an unblessed scalar I get the following:

    Use of uninitialized value in concatenation (.) or string at /home/mark/src/bif/.direnv/perl5/lib/perl5/Test/Stream/Plugin/Core.pm line 206.
    not ok 1 - ()->isa('Some::Class')
    # Failed test '()->isa('Some::Class')'
    # at x.t line 5.
    # Failed: ()->isa('Some::Class')
    # Tests were run but no plan was declared and done_testing() was not seen.

Probably you need some special casing for non-blessed arguments as well.

**Comment by mlawren** [comment]
Just to be explicit about the last point. The following:

    isa_ok [], 'Some::Class';

also results in an error:

    Can't call method "isa" on unblessed reference at x.t line 6.

**Comment by exodist** [comment]
Aright, missed that last point. This is where Test::More diverges from Test::Stream. Test::Stream introduces ref_ok to replace that usage of isa_ok. However the -Class bundle should probably have the legacy behavior, I will make that happen.

**Comment by exodist** [comment]
Test::Stream splits isa_ok into isa_ok and ref_ok. isa_ok is supposed to handle blessed references and class names, ref_ok handles any reference, but only checks reftypes.

That said there are still a few bugs in it that you have outlined:
* 'undef' needs to be handled better
* Diagnostics should not be producing warnings about concatenation
* Should not get an exception that causes an internal error when it gets bad input
* -Classic should probably have the old-style isa_ok

I will work on patching this.

**Comment by mlawren** [comment]
On Thu Nov 26, 2015 at 12:47:50PM -0800, Chad Granum wrote:
> Closed #69 via 917905b632b12115cd1dfbe0753aa90f284995b9.

Good idea with the grepable "# sub isa_ok" comments :-)

Thanks Chad for your quick and thorough response to this and my other
tickets. I am quite liking your overall design and modularity for
Test::Stream and hope it gets a foothold in the ecosystem shortly. I
have a branch in my main project using it natively and will do the same
for future ones as well.

-- 
Mark Lawrence
