### ISSUE TITLE
Plugin::Warnings refers to (missing? old?) "More" plugin

### ISSUE THREAD

**Issue by mlawren** [Test-More/Test-Stream#70]
The synopsis for the Warnings plugin says:

    # Load the Warnings plugin, and More cause we need that as well.
    use Test::Stream qw/More Warnings/;

I don't see a More plugin - I presume this is a leftover from some earlier naming scheme? Perhaps it should be Core?

**Comment by exodist** [comment]
Yes, That should be 'Core'.
