### ISSUE TITLE
Do plugins and bundles belong in the same dist as the event hub and TAP formatter?

### ISSUE THREAD

**Issue by rjbs** [Test-More/Test-Stream#74]
This is a question of whether batteries should be included.  Various threads of the conversation have touched on whether the batteries included with Test-Stream at the moment would inhibit innovation, and on whether it would be a burden on the core perl dist in some way.  We should record public discussion of this question.

**Comment by kentfredric** [comment]
I recall @shadowcat-mst mentioned something about seeing if there was an essential subset of Test::Stream that would be sufficient to support Test::Builder running on top of it:  that is, the internal Hub and things required to marshal Test::More and friends through the new sausage factory.

If this is viable, I would be interested in seeing what that looks like, simply because its inherently less ambitious and avoids prematurely locking ourselves into the user facing API of Test::Stream

**Comment by exodist** [comment]
https://github.com/Test-More/Test-Stream/pull/79

^ This is what it would look like. I would split the essential inner working into the Test-Sync dist. Then I would leave the stuff I built on top of it in the Test-Stream dist.

This is essentially a pull request of a branch with all the changes into a branch that is copy of master. Done this way for easier reviewing.

**Comment by exodist** [comment]
*Note, my branch also includes all the TAP formatter changes being reviewed in another pull request.

**Comment by kentfredric** [comment]
Hmm, that's still quite a sizeable block of code.

**Comment by exodist** [comment]
So is Test::Builder. I just don't shove it all in 1 file.

**Comment by kentfredric** [comment]
Also, why the need to rename everything? Can't you just keep the names and ship independently? Or ...  its hard to see what's going (in the file name view) on with pretty much all the files renamed.

**Comment by exodist** [comment]
Can we discuss the pull request in the pull request, and leave this ticket as the discussion on split: yes or no?

**Comment by exodist** [comment]
before taking my own advice about distributing the discussion:

Removing POD, there are 2878 lines of code post-split
There are 30 modules post-split (10 of which are events)
If lines were distributed evenly to files each file would have less than 100 lines

**Comment by rjbs** [comment]
Updated after our weekly status meeting:  Everyone has come to the agreement that this should be split, although reasons differ between people.  That's just fine!

@exodist has a branch that carries out the split (it's called "split") and applies some of the other fixes that everyone seemed to agree were the right thing.

The name of the split modules isn't 100% settled.  For now, working title is Test2.  Might stick, might not.  We'll just be focusing on the design review for now.
